http:
  port: 5001
database:
  connection_string: "dbname=postgres user=postgres password=postgres host=localhost port=5435 pool_max_conns=10"
keycloak:
  address: "https://pruebas.local.sypago.net:8443"
  admin_user: "admin"
  admin_password: "admin"
  client_id: "pgosb_admin_client"
  client_secret: "8I77PevTtR1N2b208B9s8q6x4BGOz9Nn"
  realm: "pgosb"
