http:
  port: 5001
database:
  connection_string: "dbname=postgres user=postgres password=postgres host=172.30.100.9 port=5435 pool_max_conns=10"
keycloak:
  address: "http://172.30.100.9:8442"
  admin_user: "admin"
  admin_password: "admin"
  client_id: "pgosb_admin_client"
  client_secret: "l1k4s45tKGdDx4m6GeZtBoZmYbxTfd8U"
  realm: "pgosb"

log_settings:
  console: true # Log to console (true/false)
  beutify_console: false # Format console logs for readability (true/false)
  file: true # Log to file (true/false)
  route: "logs/application.log" # Path for the log file
  min_level: "trace" # Minimum log level (debug, info, warn, error, fatal, panic)
  rotation_max_size_mb: 100 # Maximum log file size before rotation (in MB)
  max_age_day: 7 # Maximum age of log files to keep (in days)
  max_backups: 3 # Maximum number of old log files to keep
  compress: true # Compress old log files (true/false)

