http:
  port: 5001
database:
  connection_string: "dbname=postgres user=postgres password=postgres host=localhost port=5435 pool_max_conns=10"
keycloak:
  address: "http://localhost:8442"
  admin_user: "admin"
  admin_password: "admin"
  client_id: "pgosb_admin_client"
  client_secret: "oYVMKFKq5D3L5k50woQ5LSSw1waVYpRi"
  realm: "pgosb"
