http:
  port: 5000
database:
  connection_string: "dbname=postgres user=postgres password=postgres host=localhost port=5435 pool_max_conns=10"
keycloak:
  client_id: "fdms"
  client_secret: ""
  host: ""
