http:
  port: 8082
  main_domain: "pruebas.gres.net"
  enable_ssl: true
  ssl_cert: "./config/pruebas.local.sypago.net.pem"
  ssl_key: "./config/pruebas.local.sypago.net-key.pem"

database:
  connection_string: "dbname=postgres user=postgres password=postgres host=hackorlandodev.com port=5435 pool_max_conns=10"

keycloak:
  address: "http://localhost:8442"
  admin_user: "admin"
  admin_password: "admin"
  client_id: "pgosb_admin_client"
  client_secret: "l1k4s45tKGdDx4m6GeZtBoZmYbxTfd8U"
  realm: "pgosb"

log_settings:
  console: true
  beutify_console: false
  file: true
  route: "./logs/application.log"
  min_level: "trace"
  rotation_max_size_mb: 100
  max_age_day: 7
  max_backups: 3
  compress: true
